use_frameworks!
platform :ios, '9.0'

target 'JWDatePickerKit_Example' do
  pod 'JWDatePickerKit', :path => '../'
  pod 'SnapKit', '~> 4.2.0'
  target 'JWDatePickerKit_Tests' do
    inherit! :search_paths

    
  end
end
